---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    # Install the LTS version of node
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&\
    sudo apt-get install -y nodejs
    # Install n version manager to use Node-13.8.0 
    sudo npm install --global n
    sudo n 13.8.0

- name: "install pm2"
  # become: true
  npm:
    name: pm2
    global: yes
    # production: yes
    # state: present